version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: onboarding
      POSTGRES_PASSWORD: onboarding
      POSTGRES_DB: onboarding_database